openapi: 3.0.4
info:
  title: Sample API
  description: api
  version: 0.1.9

servers:
  - url: http://localhost/v1
    description: main production very much server

paths:
  /add:
    get:
      summary: 
      responses:
        '200':
          description: add a cached item
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
        '400':
          description: Invalid request (e.g., missing or invalid parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameter format for adding a cached entry: {'text': 'abc123'}"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Something went wrong on the server"
  /fetch/:id:
    get:
      summary: 
      responses:
        '200':
          description: a cached text
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    example: "my cached text"
        '400':
          description: Invalid request (e.g., missing or invalid parameters)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameter, add info {'id': 'my-cache-uuid4'} of cache"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Something went wrong on the server"
